use parkhs;

-- EMP 테이블에서 DEPTNO 조회 : 10,20,30
SELECT DISTINCT DEPTNO
FROM EMP;

-- DEPT 테이블에서 DEPTNO 조회 : 10,20,30,40
SELECT DEPTNO
FROM DEPT;

-- EMP테이블과 DEPT테이블 DEPTNO의 합집합 - UNION : 중복 제거
SELECT DEPTNO
FROM EMP
UNION
SELECT DEPTNO
FROM DEPT;

-- EMP테이블과 DEPT테이블 DEPTNO의 합집합 - UNION ALL : 중복 출력
SELECT DEPTNO
FROM EMP
UNION ALL
SELECT DEPTNO
FROM DEPT;

-- EMP테이블과 DEPT테이블 DEPTNO의 교집합 - INTERSECT
SELECT DEPTNO
FROM EMP
INTERSECT
SELECT DEPTNO
FROM DEPT;

-- DEPT테이블과 EMP테이블 DEPTNO의 차집합 - EXCEPT
SELECT DEPTNO
FROM DEPT
EXCEPT
SELECT DEPTNO
FROM EMP;



-- 테이블 구조 확인
DESC EMP;
DESC DEPT;

-- ENAME이 MILLER인 사원의 DNAME을 조회 - 2개의 쿼리 사용
SELECT DEPTNO 
FROM EMP
WHERE ENAME = "MILLER";

SELECT DNAME 
FROM DEPT 
WHERE DEPTNO = 10;


-- Sub Query 이용 - 괄호안에 서브쿼리를 먼저 수행해서 10 찾아오고 DNAME 조회
SELECT DNAME 
FROM DEPT 
WHERE DEPTNO = (SELECT DEPTNO 
				FROM EMP
				WHERE ENAME = "MILLER");
				
-- EMP 테이블에서 SAL 의 평균보다 더 많은 SAL 받는 직원 ENAME과 SAL 조회
SELECT ENAME, SAL
FROM EMP
WHERE SAL >= (SELECT AVG(SAL)
				FROM EMP);
				
			
-- EMP 테이블에서 ENAME이 'MILLER'사원과 동일한 JOB 가진 사원 ENAME과 JOB 조회
SELECT ENAME, JOB
FROM EMP
WHERE JOB = (SELECT JOB
			FROM EMP
			WHERE ENAME = 'MILLER');

-- EMP 테이블에서 DEPT 테이블의 LOC가 DALLAS인 사원과 DEPTNO가 같은 ENAME과 SAL을 조회
SELECT ENAME, SAL
FROM EMP
WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE LOC = "DALLAS");

-- EMP테이블에서 DEPTNO별 SAL의 최대값과 동일한 SAL 같은 사원의 EMPNO, ENAME, SAL을 조회
SELECT EMPNO, ENAME, SAL 
FROM EMP
WHERE SAL IN (SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO)
ORDER BY SAL;

-- EMP테이블에서 DEPTNO가 30인 데이터들의 SAL보다 큰 데이터의 ENAME과 SAL을 조회
SELECT ENAME, SAL 
FROM EMP
WHERE SAL > ALL (SELECT SAL FROM EMP WHERE DEPTNO = 30);

SELECT ENAME, SAL 
FROM EMP
WHERE SAL > (SELECT MAX(SAL) FROM EMP WHERE DEPTNO = 30);


-- EMP테이블에서 SAL 2000넘는 데이터 있으면 ENAME과 SAL 을 조회
SELECT ENAME, SAL
FROM EMP
WHERE EXISTS (SELECT 1 FROM EMP WHERE SAL > 2000 );
