# Generated by Django 4.2.3 on 2023-07-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web0726", "0002_alter_item_pictureurl"),
    ]

    operations = [
        migrations.CreateModel(
            name="product",
            fields=[
                (
                    "itemid",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("itemname", models.CharField(max_length=50)),
                ("price", models.IntegerField()),
                ("description", models.CharField(max_length=50)),
                ("pictureurl", models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name="Item",
        ),
    ]
